### ISSUE TITLE
migrate the code to kubebuilder

### ISSUE THREAD

**Issue by himanshug** [druid-io/druid-operator#106]
Last few weeks I was looking at upgrading the operator-sdk and learned that most of the things used by druid-operator have been pushed to `kubebuilder` (ref: https://www.openshift.com/blog/operator-sdk-reaches-v1.0 ) and operator-sdk now uses `kubebuilder` internally.
Besides that I got the opportunity to use `kubebuilder` on another project and found its `Makefile` based approach simpler than old operator-sdk approach where you needed operator-sdk [version specific] binary to do most things.

So, I am working on to migrate the project structure to use `kubebuilder` , that will likely also upgrade various dependency versions in the process. While this might change things for druid-operator devs, I hope to keep everything backward compatible for the druid-operator users.

**Comment by AdheipSingh** [comment]
Thanks for the update !! 

Couple of questions
- Are you planning to migrate the full dir structure to kubebuilder, meaning you'll scaffold the project using kubebuilder and migrate the code base ?
- Does this mean no use of operator-sdk cli ? 
- I locally was planning to move to operator-sdk 1.0 , does that mean we don't need to do that anymore ?
- If possible can you give an overview of the  steps you planning to achieve. 

Regardless, we can use validating webhooks easily since kubebuilder has direct cli scaffold for it +  writing integeration tests using envtest and ginko could be leveraged against a running kube api . I think the migration should be backward compatible most of the underlying libraries is controller-runtime so reconcile loop, manager should be fine.

Let me know if i can help in anycase. :)

**Comment by himanshug** [comment]
> Are you planning to migrate the full dir structure to kubebuilder, meaning you'll scaffold the project using kubebuilder and migrate the code base ?

Yes, however, we will retain all of git history of course.

> Does this mean no use of operator-sdk cli ?

Yes

> I locally was planning to move to operator-sdk 1.0 , does that mean we don't need to do that anymore ?

Yes

> If possible can you give an overview of the steps you planning to achieve.

generate empty project using kubebuilder, migrate all code to it, test .

> Do you have any estimated time line ?

hopefully have something working this week or next.

> Are you planning to move in #105 this for now ? i was hoping on 0.0.4 release.

if kubebuilder already gives us those or greater versions of dependencies then it will automatically be done as part of migration or else same work would need to happen on top.
we can still merge #105 if it is needed early and redo it on the kubebuilder version later if needed.


>using envtest and ginko could be leveraged against a running kube api

envtest is great, I don't think there is enough value in ginko for us though .. I would prefer simply using go's testing framework maybe with  https://github.com/stretchr/testify for assert/require which is very thin wrapper.

> Let me know if i can help in anycase. :)

I am sure there would always be stuff to do.

**Comment by AdheipSingh** [comment]
> we can still merge #105 if it is needed early and redo it on the kubebuilder version later if needed.

i see there are 12 commits since last release, few patches and features are their. It would be great to have kube builder changes as a purely separate release so that atleast we can use 0.0.4 for sometime in our clusters, before moving to kubebuilder one. Plus less confusion. :)

**Comment by himanshug** [comment]
I pushed the 0.0.4 release that includes #105 as well, I will re-do it if kubebuilder gets older versions.

**Comment by AdheipSingh** [comment]
> I pushed the 0.0.4 release that includes #105 as well, I will re-do it if kubebuilder gets older versions.


Thank You @himanshug :)
