### ISSUE TITLE
Detailed prod examples

### ISSUE THREAD

**Issue by dark-spark2** [druid-io/druid-operator#12]
Hi,
Could you please attach a more descriptive examples including the Console UI, middlemanager, etc.   
Example of running configuration of full prod deployment would be much appreciated.

Thanks!

**Comment by himanshug** [comment]
would it work for you if I took dump of yaml from my prod cluster, anonymized some stuff  and dumped that yaml as one [not necessarily working as is] example ?

**Comment by dark-spark2** [comment]
Yes, If you can dump an example which includes console UI and the services it would be much appreciated.
Thanks

**Comment by himanshug** [comment]
ok, I will add that  today/tomorrow . consoleUI  is part of router node that we deploy.

**Comment by Aka-shi** [comment]
@himanshug Can you please add that here. It will be of great help for us

**Comment by himanshug** [comment]
[druid-anon.yaml.txt](https://github.com/druid-io/druid-operator/files/4200633/druid-anon.yaml.txt)

Please see  the attached file that is a slightly anonymized version from one of my clusters. However, I would caution not to try and use  same as we don't use the current standard docker image from druid due to various  reasons and also Druid configuration depends on  the use cases you might have.

We use https://github.com/ksonnet/ksonnet  to generate that file for different environments (prod, staging, dev etc)  . Note that ksonnet is not a deprecated tool so you shouldn't use it, it is in our use due to the history and we will migrate  out of it to probably plain jsonnet (https://jsonnet.org/ ) as that is what we are really using under ksonnet . I wanted  to just let you know that yaml doesn't have to be hand-crafted.

**Comment by Aka-shi** [comment]
Hey, Thanks so much. This clears many of my doubts regarding the operator. However
``we don't use the current standard docker image from druid due to various reasons``,  do you mean the current official image for druid 0.17.0 has issues and cannot be used in production or it doesn't work well with operator? If not are there any public images that you can suggest? Thank you.

**Comment by AdheipSingh** [comment]
@dark-spark2  Here is one which i am using https://gist.github.com/AdheipSingh/9791655b8ea063fe27dcac5e0fcbea8c. Hope this finds you helpful

**Comment by EmiPhil** [comment]
This left me confused for a bit so in case it helps future people:

When setting the options in runtime properties make sure to use [yaml's block scalar](https://yaml-multiline.info/) with newline ( | ), eg.:
```yaml
      runtime.properties: |
        ...
        configstuff
        ...
```

One of my runtime properties was using block scalar with no newline ( |- ). eg.:
```yaml
      runtime.properties: |-
        ...
        configstuff
        ...
```

Which was causing errors because druid appends `druid.host=${host}` to the properties file and without a newline at the end of the file will it will append that directly to the last property you configured, eg.

```
druid.property=valuedruid.host=127.0.0.1
```

instead of

```
druid.property=value
druid.host=127.0.0.1
```

**Comment by aelmanaa** [comment]
hello @himanshug @AdheipSingh  thank you very much for your files. is there any documentation to write the specs , except the source code? :)

**Comment by AdheipSingh** [comment]
@himanshug i can surely submit a PR on documentation. 

@aelmanaa

**Comment by AdheipSingh** [comment]
@himanshug I can add a PR for the docs. It would be great to list  out some specifications.

**Comment by himanshug** [comment]
sure, documentation that helps users is  great to have.

**Comment by AdheipSingh** [comment]
@himanshug this can be closed i guess :)
