### ISSUE TITLE
Document what the operator does

### ISSUE THREAD

**Issue by jeremydonahue** [druid-io/druid-operator#13]
Hi there, I'm hoping you could add some documentation on the features this operator provides. Obviously it creates a druid cluster, but what else does it do? Why should I use this? Thanks!

**Comment by AdheipSingh** [comment]
To answer you query, what operators leverage is basic install, seamless upgrades, running applications in autopilot mode, lifecycle management and deep insights.
 Currently the druid operator helps us with basic install, we need to maintain a single spec CR, which is responsible for the state of the whole druid cluster. 

Since this is an alpha release with time, more features shall be added. 
Documentation is present for getting started, go ahead and try out. 

@himanshug correct me if i am wrong.

**Comment by himanshug** [comment]
going by  the operator capacity level described in https://github.com/operator-framework/operator-sdk#operator-capability-level , currently druid-operator does...

Phase-I : Basic Install - In fact very sophisticated installs are possible with different nodes running different druid versions, configurations e.g. you can have two sets of brokers running different versions of Druid and different configurations etc)

Phase-II : Seamless Upgrades , current  operator does support upgrades to a good degree. That  said, I believe, there  are many different variants of upgrading things and all of them might  not be possible and  it would be good  to get issues that people face while upgrades and fill those missing gaps.

Phase-III : App Lifecycle and Storage Lifecycle (backup , failure recovery) - Currently operator does not do anything special with respect to backup, which I think Druid automatically handles due to its usage of external RDBMS and DeepStorage  having  their own backup and disaster recovery strategies. All state stored in Druid nodes is transient. Operator does support fault tolerant in the sense if pods die or other resources managed by  operator get deleted etc then operator would automatically re-create those.

Phase-IV : Deep Insights (Metrics, Alerts, Log Processing and Workload Analysis) - I think Druid itself (via its emitter extensions)  and K8S  infrastructure extensibility for logs/metrics management (fluentd, prometheus etc) have lots of capabilities to enable those. So, operator  doesn't do anything special here for now. However operator does expose its own logs and events to enable users debugging problems in the operator itself.

Phase-V : Auto Pilot (Horizontal/Vertical Scaling, auto config tuning, abnormal detection, scheduling tuning) - None of that currently exists but support for Horizontal autoscaling via  https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/ is on the way, see https://github.com/druid-io/druid-operator/pull/11

That said, I would be supporting of learning about concrete real world use cases for any of the features that might be missing and would like to add those. 

> Documentation is present for getting started, go ahead and try out.

I totally agree :)


did that help ?

**Comment by ChethanUK** [comment]
> DeepStorage that have their own backup and disaster recovery strategies

What do you mean? Consider DeepStorage is HDFS or GCS if you delete the file it's gone right?

> Operator does support fault tolerance in the sense
I didn't understand, if one of the druid node goes down and K8s cluster doesn't have the resource what will happen?

**Comment by AdheipSingh** [comment]
@ChethanUK 
The operator maintains the state  which is a  Custom Resource, the operator is acts as non terminating control loop that shall regulate the state of your CR Spec at all times. So lets say you have 3 replicas for druid brokers mentioned in your spec, accidentally you issue the command ```kubectl delete deploy broker```, the operator will recreate the deployment again since the CR Spec mentions in particular 3 nodes for the broker. So this way we are able to achieve a fault tolerant, the example i gave of replicas holds the truth for all the other resources deployed by the operator such as services, PDB etc. I suggest in order to understand the  kindly go through the custom controllers and their working with respect to kubernetes.

Deep Storage is where all your segments are stored, this is a storage mechanism. Druid is responsible for offloading the data to deepstorage which further queryable through your historicals.
Druid is not responsible for maintaing availability of your deepstorage as long as druid sees your deepstorage up it shall store all the segments, irrespective of how many nodes go down in druid.

In distrubted systems, each component has its own way of scaling, availability.....druid is a distributed data store which at core follows those principles.

I hope i able to explain your query.

**Comment by himanshug** [comment]
> What do you mean? Consider DeepStorage is HDFS or GCS if you delete the file it's gone right?

Backup/Recovery of external dependency shouldn't really be a concern of Druid or druid-operator. Druid depends  on those for those exact reasons. However,
AWS S3:  supports  object versioning (we  use it) that allows you to revert back just in case something is accidentally deleted.
GCS: I haven't used GCS but  https://cloud.google.com/storage/docs/object-versioning claims versioning support.
HDFS: I used it a  lot in my previous job , there  is no versioning but it has snapshots support which is a close relative.
All of them are highly available and reliable systems.
For critical services, we even do multiple deployments of clusters in different data centers and feed same input data to both to not have single cluster  as a SPOF .

> I didn't understand, if one of the druid node goes down and K8s cluster doesn't have the resource what will happen?

That problem is not druid-operator specific and could happen to  any application pods on K8S cluster. K8S has mechanisms to setup monitoring and alerting for those situations, e.g. if we submit a pod and  k8s is running out of resources to run it then we get alerts. There would  be logs as well from different components in K8S.

**Comment by ChethanUK** [comment]
> HDFS: I used it a lot in my previous job, there is no versioning but it has snapshots support which is a close relative.

Yes. HDFS doesn't have versioning..

Only doubt if incase for example while having rolling update from say 0.17 to 0.18 and one pod's crash loop and etc.. etc.. and corrupt the segments what to do was the concern (too extreme)


> K8S has ways to dynamically increase the number of nodes

Same in all cloud K8s from gke to aks etc..

**Comment by ChethanUK** [comment]
Also, Will crd templates created for common things like ingestion (loading from [Kafka](https://druid.apache.org/docs/latest/tutorials/tutorial-kafka.html#submit-a-supervisor-directly) and [Hadoop](https://druid.apache.org/docs/latest/tutorials/tutorial-batch-hadoop.html))?

**Comment by himanshug** [comment]
> Also, Will crd templates created for common things like ingestion (loading from Kafka and Hadoop)?

you mean is  there a way to put in spec given to druid-operator that "start this kafka/hadoop indexing" ? No, druid-operator only deploys/manages the Druid cluster . Creating/Submitting/Managing druid tasks for indexing is out of scope or I missed what you meant.

**Comment by fzhan** [comment]
Would it be possible to add a example for multi-node cluster? I'm using microk8s for the k8s cluster, and cephfs for storage class. Any lights would be wonderful.
