### ISSUE TITLE
Statefull Sets for Master Nodes

### ISSUE THREAD

**Issue by AdheipSingh** [druid-io/druid-operator#17]
I am having a small doubt since this operator creates all the druid services as statefulsets, do we really need to have statefull set for coordinators and overloads. Is it necessary to use a persistence such as ebs for it, or something such as hostPath or emptyDir should do the job as well.

**Comment by himanshug** [comment]
StatefulSet  is not strictly necessary for all node types , however it keeps code and deployment  simple because  user only need to learn about StatefulSet . I  couldn't  see any pressing reason to choose a different controller for nodes where  StatefulSet  wasn't strictly necessary.

EBS is not necessary for coordinator/overlord but I  tend to use ebs to preserve gc logs and  heap dumps that I configure jvm  to send to that specific location in EBS so that they would survive even if pod/k8s-node went away for me to be able to debug things.

**Comment by AdheipSingh** [comment]
@himanshug thank you for the response.
