### ISSUE TITLE
Rolling Deploy Stuck

### ISSUE THREAD

**Issue by AdheipSingh** [druid-io/druid-operator#26]
I did an update in a running druid cluster, what i notice is the historicals do not come up , on describing the druid cluster,  here is what i see. Trying to understand the output, does this mean that the updated historical pod is trying to get all the segments which were in the older historical pod ?
Since historical are the first process to get updated, the other druid process are stuck.
Not sure what is happening
```
Events:
  Type    Reason                   Age   From            Message
  ----    ------                   ----  ----            -------
  Normal  UPDATE_SUCCESS           8m    druid-operator  Updated [ConfigMap:cluster-druid-common-config].
  Normal  UPDATE_SUCCESS           8m    druid-operator  Updated [StatefulSet:druid-cluster-historicals].
  Normal  ROLLING_DEPLOYMENT_WAIT  8m    druid-operator  StatefulSet[druid-cluster-historicals] roll out is in progress CurrentRevision[druid-cluster-historicals-75c77695db] != UpdateRevision[druid-cluster-historicals-844d58fc54], UpdatedReplicas[0/824650262508]
  Normal  ROLLING_DEPLOYMENT_WAIT  8m    druid-operator  StatefulSet[druid-cluster-historicals] roll out is in progress CurrentRevision[druid-cluster-historicals-75c77695db] != UpdateRevision[druid-cluster-historicals-844d58fc54], UpdatedReplicas[0/824648533800]
  Normal  ROLLING_DEPLOYMENT_WAIT  8m    druid-operator  StatefulSet[druid-cluster-historicals] roll out is in progress CurrentRevision[druid-cluster-historicals-75c77695db] != UpdateRevision[druid-cluster-historicals-844d58fc54], UpdatedReplicas[0/824646252040]
```

**Comment by himanshug** [comment]
that is expected behavior, when "rollingDeploy: true" is set in spec then operator tries to follow strictly updating in the order mentioned in https://druid.apache.org/docs/latest/operations/rolling-updates.html
if historicals can't come up after update for whatever reasons, then it wouldn't progress to update other sts .. that is what  you want with rolling deployment.

you can choose to not have that behavior by removing "rollingDeploy" from your spec.

or if you know what the problem is and wanna just deploy whole thing, manually delete all stateful-sets and operator would re-create all of them.

**Comment by AdheipSingh** [comment]
Thank you, i resolved it
