### ISSUE TITLE
Support StatefulSet only For Historicals,MM

### ISSUE THREAD

**Issue by AdheipSingh** [druid-io/druid-operator#49]
### Description
- Currently the operator provisions statefulset for all the druid processes, regardless of their nature (stateless/statefull )
- Brokers, routers, coordinators, overlords are stateless in nature and don't require a persistence. 
- Statefulsets have their own challenges such as sts does not support rollbacks ( since their is no replicaset associated with sts ), pvc's remain in not reference/hanging state during scale up/down of pods ( though ideally operator should address this problem https://github.com/druid-io/druid-operator/issues/43 ). At time sts need to be manually deleted using cascade options.
- The operator should support deployment objects for all process accept MM/Historicals.
- The current druid_controller can reconcile against deployment events, we don't need a separate controller.
- As discussed earlier https://github.com/druid-io/druid-operator/issues/17, mostly logging solutions such as fluentd, dd agents running as daemonsets can push logging to external datastores for querying. Using EBS for logging can be an option not necessity, 
- https://github.com/druid-io/druid-operator/blob/master/pkg/controller/druid/handler.go#L537 this func needs to be split up for seperate podSpec and podTemplateSpec which can be used as common to both deployments.sts. 
- https://github.com/druid-io/druid-operator/blob/master/pkg/controller/druid/handler.go#L133, a conditional check on the basis of nodeType can be used whether to deploy deployment or sts.
- Implementing these changes on existing cluster may require manual intervention. 
------------------------------------------------------------------------------------------------------------------------------
@himanshug

**Comment by ChethanUK** [comment]
> * all the druid processes, regardless of their nature (stateless/statefull )

ya, I had the same point before, why have stateful for those which can be just stateless...


> * sts does not support rollbacks

Yup, do face these problems



> * manual intervention

Operator shud have minimal manual involvement (I thought that was the goal of the operators)

**Comment by AdheipSingh** [comment]
Here a sample working  implementation for the tiny spec.
https://github.com/AdheipSingh/druid-operator/blob/deployment/pkg/controller/druid/handler.go

**Comment by vDMG** [comment]
Would be nice to use the appropriate workload, indeed have STS for all workload is overkilling and block some nice feature form Deployment workload.

> Brokers, routers, coordinators, overlords are stateless in nature and don't require a persistence.

👍 

> As discussed earlier #17, mostly logging solutions such as fluentd, dd agents running as daemonsets can push logging to external datastores for querying. Using EBS for logging can be an option not necessity,

We shouldn't use STS because of logging issues, indeed this issue is for cluster administrators not this operator.

> Implementing these changes on existing cluster may require manual intervention.

You mean that for an existing cluster it would be necessary may be deleting old STS manually to properly upgrade the operator ?

**Comment by himanshug** [comment]
glad to see the lively discussion and a community :)

so, it is clear that we can't avoid StatefulSet (at least for historical and middleManager nodes), so all the problems associated with them have to be dealt with either by manual intervention or whatever can be automated/fixed.

Beyond that, from discussion above I see two proposed advantages of `Deployment` resource where possible ( .. please list  if I missed any)

1. `Deployment` allows "roll back" while `StatefulSet` doesn't ? I suppose you are talking about https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#rolling-back-a-deployment  . Would that not require manual intervention to roll  back  to and older revision and also would operator not just revert back to latest version   that it thinks is correct ?

2. `StatefulSet` doesn't delete PVCs.. Does `Deployment` delete the PVCs associated  as it scales up and the down ?

**Comment by AdheipSingh** [comment]
@himanshug thank you for replying :) 

1. Here a imp point which might help us to bring **helm** into play. Any manual innervation directly to deployment/sts is not to be done as per best practices.( anyways operator will reconcile it back ) In case of any changes whether rollback/apply etc all must happen directly to the CR as it holds the state of the cluster. 
We should deploy our CR using helm charts (helm maintains a specific revision for each chart deployed ) the operator just reconciles the state.
Example:
```
adheip@adheip:~$ helm ls -A
NAME                            	NAMESPACE         	REVISION	UPDATED                                	STATUS  	CHART                      	APP VERSION             
druid                    	default           	22      	2020-05-26 14:44:02.15281 +0530 IST    	deployed	druid-0.0.1        	latest                  
```
1. Helm deploys the CR
2. Operator sees the CR and reconciles the state
3. Helm does rollback to revision 21
4. Operator again reconcile the state.
- Drawback here is the helm rollback requires a manual eye, how can we automatically rollback a particular CR to previous prevision without any manual innervation ? Plus what are the criteria for a  rollback need to be defined. The issue here is operator does not store any manifests, in k8s the etcd stores all the manifests following optimistic concurrency using ```ResourceVersion```  .  Most of the managed services don't have etcd available to user. 
- When deployment creates replicas sets are created and pods have owner-reference of replica set which in turn have for deployments. This param in deployment ```deployment.kubernetes.io/revision: "13"``` is responsible for rollback. 
- So when we use deployment the previous replicaset associated with the deployment is scaled up, with sts its deleted and recreated. 

2. PVC's are independent of any object. They will not be deleted in case of deployment, but the point here is deployments are stateless in nature and for druid specific use case **we don't need pvc's**. ( apart from historical/MM)
Plus deletion of PVC's is an issue, and we might need to have some custom logic which checks the unreferenced/unmounted pvc's. Ill comment in detail on #43.

3. The other issue i see is with sts is updateStrategy which is parallel or ordered, deployments rolling Update are more flexible after tuning the ```maxSurge``` , ```minSurge``` params. 

4. Statefulsets only to be used with tightly coupled usecases, since historicals and MM both need to serve segments in real time / after handoff . Its still easier to maintain two sts than 5-6 sts. Brokers is one component which can be scaled smoothly with deployments.

**Comment by AdheipSingh** [comment]
> > Implementing these changes on existing cluster may require manual intervention.
> 
> You mean that for an existing cluster it would be necessary may be deleting old STS manually to properly upgrade the operator ?

i meant that lets say now the operator supports deployments, in that case the already running statefulsets for druid nodes ( pods ) may require manual deletion. For an existing cluster having all druid nodes as sts we might need to do certain deletions manually still not sure how will it work on existing cluster. @vDMG

**Comment by himanshug** [comment]
- argument related to PVCs really doesn't apply because they don't exist in `Deployment` , with `StatefulSet` they are totally optional and user can choose to not use PVCs and get behavior similar  to `Deployment` .

 - Both, `Deployment` and  `StatefulSet` support rolling upgrade but `Deployment`  does have advantage there mainly due to...
1. StatefulSet sometimes,  on rolling update, require manual force deletion of pods due to the known bug   https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#forced-rollback .
2. StatefulSet can either upgrade one pod at a time or all in parallel while Deployment provides more knobs with https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#proportional-scaling

(2) is helpful when we can use `Deployment` with a nodeType that has many pods which happens to be the case for Historicals and MiddleManagers in Druid cluster, however we would still be using `StatefulSet` there.
Coordinator/Overlord pods are generally 2 or maximum 3, so (2) doesn't help here.
Someone could have many Brokers where (2) could be advantageous but I'm not sure how much really.

regarding (1), that  bug in StatefulSet sucks and is a legit argument to use `Deployment` where possible to reduce manual intervention.

So, I can see the love for `Deployment` there. I also looked at the code complexity introduced due to this ( patch in https://github.com/druid-io/druid-operator/issues/49#issuecomment-633239182 ) which doesn't look to be too bad. So I am +1  for using `Deployment`  however please make it possible for user to still force use of `StatefulSet` (to allow backward compatibility and also some, like me, might just prefer the uniformity )

**Comment by AdheipSingh** [comment]
@himanshug thanks for taking a look at the patch. 
Though i am not sure how to force user of sts, maybe give an option to specify type as Deployment or sts in types.go ?
ill raise a PR, maybe it will be more clear, once the patch is finalised.
Thanks a lot for giving this a green light. :) :)

**Comment by hgupta-splunk** [comment]
yeah, I meant having a configuration something like `k8sResourceType` in the nodSpec probably... haven't thought it through  though.

**Comment by himanshug** [comment]
yeah, I meant having a configuration something like k8sResourceType in the nodSpec probably... haven't thought it through though.
