### ISSUE TITLE
allow custom sidecar containers & initContaniers

### ISSUE THREAD

**Issue by exherb** [druid-io/druid-operator#59]

**Comment by AdheipSingh** [comment]
what is the usecase ? please give some description. @exherb

**Comment by exherb** [comment]
integrated with https://github.com/opstree/druid-exporter?

**Comment by AdheipSingh** [comment]
i see, in case you are trying to run as a sidecar, their should be a mutating web hook to inject side-cars. Not sure why the operator should support it. Operator supports pod annotations, you can apply those annotations to inject sidecars.

**Comment by exherb** [comment]
> i see, in case you are trying to run as a sidecar, their should be a mutating web hook to inject side-cars. Not sure why the operator should support it. Operator supports pod annotations, you can apply those annotations to inject sidecars.

ok, some cluster may not support this.

**Comment by himanshug** [comment]
> their should be a mutating web hook to inject side-cars

while that can be done, it is very cumbersome because it probably requires a new mutating admission controller and hence needs to be enabled by k8s cluster administrators ... in most cases, teams deploying applications like Druid are different from teams managing k8s cluster ... and a custom admission controller for injecting a Druid specific side-car would be a major ask...... . so IMHO, having ability to add sidecars or init containers might be a nice option.

it could also be used to do things like create few necessary directories before Druid container starts up.

**Comment by AdheipSingh** [comment]
@himanshug 
as per istio usecases, we either label the namespace with a particular label or specify annotation in the deployment/sts spec to enable sidecar injection. In case we have or replicate something on druid side for istio or X service mesh usecase most of them is possible by just adding podAnnotation. 
I am still not sure how can we add sidecars, since we dont know the nature/purpose of the sidecar. 
As far init container is concerned i think we can just support init container in the spec at both cluster + node level. Directories structure can also be fixed modifying the druid entrypoint in Docker but regardless of that init containers can be leveraged :) 

Can you come up with some more exact sidecar implementation usecase ? like how are you planning to support in the operator,  in case we knew for example we need to run an nginx sidecar we could have done that but supporting any random sidecar...... not sure how is that possible. 
 
Plus i need to  add validating webhook, so having mutation webhook can work almost the same way.  but before that we need to know what object are we mutating and whats usecase for that.

Sounds interesting discussion though, we can move this too any issue or re-open this  :)

**Comment by himanshug** [comment]
at this point all of this is nice-to-have that is why I did not re-open the issue.

for directory creation, yes it is doable via the start script in docker container ... init container would only provide a much more generic version of that.

we can/would do this when must-have use cases show up I guess.

**Comment by achetronic** [comment]
I would like to reopen this issue. The reasons are the following:

1. When you use the Helm chart with dependencies needed by Druid, for example, PostgreSQL as metadata storage, you need to deploy the postgres before Druid and you have to be sure about it is deployed. 

2. Helm is not able to wait for dependencies to be ready so one possibility would be to inject an initContainer with just a delay or a command to query postgres in order to know when Postgres and ZooKeeper are ready, then the initContainer would finish execution and Druid would start the deployment knowing the dependencies are ready

By the moment, joining them together don't fail because Druid's image is as big as postgres and zookeeper deployment get ready earlier, but this is not a reliable approach.

When talking about FluxCD deployment, you can achieve this goal splitting the deployment into two different HelmReleases but this don't make sense because you need to sync not only the deployment but the credentials. If you use, for example ExternalSecrets to get secrets from Vault, you can overwrite the Secret resources for Kubernetes, used by both (PostgreSQL and Druid metadata config), but what about username? Druid does not implement a PasswordProvider for metadata's username, and postgreSQL Helm get the username from the values yaml file. With this approach you need to sync both them in order not to store username in any place but having the same in the both applications. 

This can not be done using YAML anchors to reference the same string, because different HelmReleases are two different YAML files so finally, to be production ready and can be managed by large companies like mine, we need initContainer. 

Please, reconsider its inclusion
