### ISSUE TITLE
RoadMap for Operator

### ISSUE THREAD

**Issue by AdheipSingh** [druid-io/druid-operator#6]
@himanshug can we add a roadmap for this operator. Some contribution guidelines, how can we handle seamless version upgrade, and maybe running auto pilot. Can you highlight those.

**Comment by himanshug** [comment]
thanks @AdheipSingh 

most important item is to setup a build so that PRs submitted run a build that at least compiles the code and runs the unit tests etc. it would be great to have additional "integration-test" sort of build that actually deploys a druid cluster.

aside from that, for features, I would let it evolve organically based on use cases that people come across as we get more adoption.

feel free to create bugs or post questions here, I will try to reply if those could be achieved with existing features or else we can add the features necessary. Only thing is that, I like adding features  driven by real needs.

I am traveling this month, so maybe slow in replying.

**Comment by himanshug** [comment]
in terms of contributing guidelines , we will pretty much follow same model as Druid project. Only difference being this is not a java project so java specific things don't apply.

**Comment by AdheipSingh** [comment]
@himanshug thanks for the reply. I agree on your points. I plan to add some testing suites which i am still in a process of testing those out. I can surely help you in setting a CI with those suits included. We need to have go lint also. Great, keep me posted on when we can apply the above. :)

**Comment by himanshug** [comment]
I used golint in another project in the past and used to fail builds with it. but, decided to abandon it for following reason... (no knobs to adjust things)

`
The suggestions made by golint are exactly that: suggestions. Golint is not perfect, and has both false positives and false negatives. Do not treat its output as a gold standard. We will not be adding pragmas or other knobs to suppress specific warnings, so do not expect or require code to be completely "lint-free". In short, this tool is not, and will never be, trustworthy enough for its suggestions to be enforced automatically, for example as part of a build process.
`

Ref: https://github.com/golang/lint/blob/master/README.md#purpose

**Comment by AdheipSingh** [comment]
agreed, do tell how i can help in creating this whole process. Ill be posting my suggestions as i proceed. Do keep me in sync. Looking forward to contribute.
