### ISSUE TITLE
Integration Test Suite

### ISSUE THREAD

**Issue by AdheipSingh** [druid-io/druid-operator#7]
On the basis of this https://github.com/kubernetes-sigs/kubebuilder/tree/master/docs/testing.
I am planning to add test case for druid_types.go. Two specs which are to be tested is the DruidClusterSpec and DruidNodeSpec, what to assert is the // Required Params in the structs //.
Here is a sample playaround code.
```
package v1alpha1_test

import (
	. "github.com/onsi/ginkgo"
	. "github.com/onsi/gomega"

	"golang.org/x/net/context"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"

	. "github.com/druid-io/druid-operator/pkg/apis/druid/v1alpha1"
)

var _ = Describe("Druids", func() {
	var (
		key              types.NamespacedName
		created, fetched *Druid
	)

	BeforeEach(func() {
		// Add any setup steps that needs to be executed before each test
	})

	AfterEach(func() {
		// Add any teardown steps that needs to be executed after each test
	})


	// Avoid adding tests for vanilla CRUD operations because they would
	// test Kubernetes API server, which isn't the goal here.
	Context("Create API", func() {

		It("should create an object successfully", func() {
			key = types.NamespacedName{
				Name:      "foo",
				Namespace: "default",
			}
			created = &Druid{
				ObjectMeta: metav1.ObjectMeta{
					Name:      "foo",
					Namespace: "default",
				},
				Spec: DruidClusterSpec{
                                      // Add all the params to be tested
					JvmOptions: "",

				}}

                        // test same for nodespec
                       // add another context for nodespec
			By("creating an API obj")
			Expect(k8sClient.Create(context.TODO(), created)).To(Succeed())

			fetched = &Druid{}
			Expect(k8sClient.Get(context.TODO(), key, fetched)).To(Succeed())
			Expect(fetched).To(Equal(created))

			By("deleting the created object")
			Expect(k8sClient.Delete(context.TODO(), created)).To(Succeed())
			Expect(k8sClient.Get(context.TODO(), key, created)).ToNot(Succeed())

		})

	})

})
```
Any specifics which you feel needed to be looked upon...... @himanshug @akashdw

**Comment by himanshug** [comment]
I quickly read through https://github.com/kubernetes-sigs/kubebuilder/tree/master/docs/testing which describes "integration tests" where a k8s API server (with etcd) is spun up to do the testing and "e2e tests" which is targeted towards testing with a remote k8s cluster.
However, code snippet, you posted above looks like "unit tests" with a mock k8sClient .
Did I get it right ?

FYI, we have some UTs in https://github.com/druid-io/druid-operator/blob/master/pkg/controller/druid/handler_test.go as well.

all said, UTs are good to have of course as they run fast. I loved the "integration tests" idea described in https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/testing/integration.md even more because mocks assume you know what to expect, running something against a real API server gives even higher level of confidence.
If possible, It would be great if we could write the test suite in a way that lets us run same tests in the unit test mode with mock k8sClient and run them in integration tests mode against locally running API server.

**Comment by AdheipSingh** [comment]
@himanshug yes my code snippet was more or less targeted just for testing the types using the client. I agree with you on the part of having the tests run against real API server. So to sum we should have integration test ( which more of a unit test ) + have a e2e test ( run it against API Server ) as described in the docs.
