### ISSUE TITLE
Pod Not Getting Re-Loaded After CR Updated

### ISSUE THREAD

**Issue by AdheipSingh** [druid-io/druid-operator#79]
- The operator maintains a hash which is associated at the metadata annotation level and at configMap in  env vars of pods.
- Mainly to reload the configs if any change happens in the any of the object  reconciled by the operator ( any object using runtime.object interface )

ISSUE

- I applied a wrong config to my Druid CR which resulted in cold historical node running as sts to fail, which led to crashing state. The operator rightly halt the updates since rolling Deploy was true.
- After i applied the right configuration to Druid CR their was no trigger of a new sts or pod by the operator. I had to manually delete the sts for the new configs to be applied. 

- I am curious why dint the operator re-load the config, since on debug the prev hash and new hash were different. 
- I believe the annotations for hash should be maintained at the pod level ( pod template metadata ), i havent tested out this approach, but i see that helm is also hashing configurations at the pod level and not sts/deploy metadata.

- Not sure if this is a desired behavior or something wrong in the operator. 

NOTE: This behavior i only see for sts when on crashing state, after new configs applied the pod still remains in crashing state and does not restart/reload the new cm updates

@himanshug

**Comment by himanshug** [comment]
config reload is not done by the operator but by the k8s itself , we put the config hash as env variable so that k8s can note the change and restart pods mounting those configMaps as volume.

When you changed the config, did operator update the StatefulSet with new hash in the pod template env variable ? It should, as that is what is operator's responsibility. If that didn't happen, then we have a bug somewhere.

if operator did its job, then most likely, you have hit https://github.com/kubernetes/kubernetes/issues/67250 (mentioned in https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#forced-rollback  as well) which is really a k8s problem. if this scenario can be auto-detected reliably then we can possibly make an exception (same as https://github.com/druid-io/druid-operator/issues/76 ) and auto delete-recreate the StatefulSet . But, this is really an inherent k8s issue, and maybe we can just document it only so that user know what to expect like k8s docs itself do.

**Comment by AdheipSingh** [comment]
i think you are right, it's a statefulset issue, ill still confirm it once more by re-creating this issue and if we go into a crashloopback we can do the sdk.Delete() path ( i have that working for #76, need to test it once ) .
Yes i had printed out the hashes current obj and prev obj both were unique, though will confirm the k8s env part.
