### ISSUE TITLE
Log when spec is invalid

### ISSUE THREAD

**Issue by AdheipSingh** [druid-io/druid-operator#98]
Operator not logging, just sending an event if spec is invalid.
can add a logger.Error here
```
	if err := verifyDruidSpec(m); err != nil {
		e := fmt.Errorf("invalid DruidSpec[%s:%s] due to [%s]", m.Kind, m.Name, err.Error())
		logger.Error(e, e.Error(), "name", m.Name, "namespace", m.Namespace) 
		sendEvent(sdk, m, v1.EventTypeWarning, "SPEC_INVALID", e.Error())
		return nil
	}
```

**Comment by himanshug** [comment]
curious what prompted it , same information is going to event and `kubectl describe` would show it immediately .. which should also be the first place to refer for debugging.

would that log not unnecessarily pollute the operator log when same information is already available elsewhere ?

**Comment by AdheipSingh** [comment]
ah so the issue is, we usually push log to a central system for query/storage..... somehow events aren't going their, plus they are short lived, in case i would like to see what messed up a day back, they aren't visible. That what the only reason. Rest is fine, since will be anyways moving to OPENAPI or webhook.

**Comment by AdheipSingh** [comment]
@himanshug just a question about logging, dont you think the operator printing out the whole spec is just confusing ?
like id like to understand the specific reason for printing current/updated object ? druid has soo large configs that it just adds more complexity to see the logs.....

**Comment by himanshug** [comment]
> we usually push log to a central system for query/storage..... somehow events aren't going their,

all k8s events are also logged by k8s itself and could be sent to the log storage system ... we actively did that as k8s logs are useful for many other things anyways.

>  just a question about logging, dont you think the operator printing out the whole spec is just confusing ?

you mean we print whole objects when some error happens ? yeah, it can become verbose when encountering errors .. I think I didn't have a good way to do the "diff" but I liked having more information available than less ie. full spec that operator tried to give to k8s that failed .... I think the problem is that it keeps on printing same error on each reconcile loop which is continuously retried ... we can probably silence the logging if they have been happening repeatedly for same CR.

**Comment by AdheipSingh** [comment]
yeah i do have logs, my concern was events needs to be pushed, anyways i ll figure that out

Maybe we can verbose option enabled, not sure if the current logger( logF ) package supports that.

**Comment by himanshug** [comment]
we can add the log, nothing against that as it is only printed on validation failure ... was just curious why events weren't enough.
events are logged by k8s itself, not a logger thing.
